import { useClient } from 'next/client';
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "../../Components/Component_index";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  useClient();
  return (
    <html lang="en">
      <Navbar/>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
